[package]
name = "mender-api-cfg"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
mender-api = { path = "../api", features = ["clap"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"

[lints]
workspace = true
